## See also ../roles.yml and ../spawners.yml

### Nanotrasen Visitors with Nanotrasen ID

# Command
# Following use EventHumanoidMindShielded since they are heads and probably should have mindshields

- type: randomHumanoidSettings
  id: VisitorHead
  parent: EventHumanoidMindShielded
  components:
    - type: GhostRole
      name: ghost-role-information-disaster-victim-name
      description: ghost-role-information-disaster-victim-description
      rules: ghost-role-information-disaster-victim-rules
      raffle:
        settings: default

- type: randomHumanoidSettings
  id: VisitorCaptain
  parent: VisitorHead
  components:
    - type: Loadout
      prototypes: [ VisitorCaptain, VisitorCaptainAlt ]

- type: randomHumanoidSettings
  id: VisitorCE
  parent: VisitorHead
  components:
    - type: Loadout
      prototypes: [ VisitorCE, VisitorCEAlt ]

- type: randomHumanoidSettings
  id: VisitorCMO
  parent: VisitorHead
  components:
    - type: Loadout
      prototypes: [ VisitorCMO, VisitorCMOAlt ]

- type: randomHumanoidSettings
  id: VisitorHOP
  parent: VisitorHead
  components:
    - type: Loadout
      prototypes: [ VisitorHOP, VisitorHOPAlt ]

- type: randomHumanoidSettings
  id: VisitorHOS
  parent: VisitorHead
  components:
    - type: Loadout
      prototypes: [ VisitorHOS, VisitorHOSAlt ]

- type: randomHumanoidSettings
  id: VisitorResearchDirector
  parent: VisitorHead
  components:
    - type: Loadout
      prototypes: [ VisitorRD, VisitorRDAlt ]

- type: randomHumanoidSettings
  id: VisitorQM
  parent: VisitorHead
  components:
    - type: Loadout
      prototypes: [ VisitorQM, VisitorQMAlt ]

# Security
# Following use EventHumanoidMindShielded since they are heads and probably should have mindshields

- type: randomHumanoidSettings
  id: VisitorSecurity
  parent: EventHumanoidMindShielded
  components:
    - type: GhostRole
      name: ghost-role-information-disaster-victim-name
      description: ghost-role-information-disaster-victim-description
      rules: ghost-role-information-disaster-victim-rules
      raffle:
        settings: default

- type: randomHumanoidSettings
  id: VisitorSecurityCadet
  parent: VisitorSecurity
  components:
    - type: Loadout
      prototypes: [ VisitorSecurityCadet, VisitorSecurityCadetAlt ]

- type: randomHumanoidSettings
  id: VisitorSecurityOfficer
  parent: VisitorSecurity
  components:
    - type: Loadout
      prototypes: [ VisitorSecurityOfficer, VisitorSecurityOfficerAlt ]

- type: randomHumanoidSettings
  id: VisitorDetective
  parent: VisitorSecurity
  components:
    - type: Loadout
      prototypes: [ VisitorDetective, VisitorDetectiveAlt ]

- type: randomHumanoidSettings
  id: VisitorWarden
  parent: VisitorSecurity
  components:
    - type: Loadout
      prototypes: [ VisitorWarden, VisitorWardenAlt ]

# Misc

# Cargo

- type: randomHumanoidSettings
  id: VisitorCargoTechnician
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorCargoTech, VisitorCargoTechAlt ]

- type: randomHumanoidSettings
  id: VisitorSalvageSpecialist
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorSalvageSpecialist, VisitorSalvageSpecialistAlt ]

# Engineering

- type: randomHumanoidSettings
  id: VisitorAtmosTech
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorAtmosTech, VisitorAtmosTechAlt ]

- type: randomHumanoidSettings
  id: VisitorTechnicalAssistant
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorTechnicalAssistant, VisitorTechnicalAssistantAlt ]

- type: randomHumanoidSettings
  id: VisitorEngineer
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorEngineer, VisitorEngineerAlt ]

# Medical

- type: randomHumanoidSettings
  id: VisitorMedicalIntern
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorMedicalIntern, VisitorMedicalInternAlt ]

- type: randomHumanoidSettings
  id: VisitorMedicalDoctor
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorMedicalDoctor, VisitorMedicalDoctorAlt , VisitorScrubsPurple, VisitorScrubsGreen, VisitorScrubsBlue]

- type: randomHumanoidSettings
  id: VisitorParamedic
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorParamedic, VisitorParamedicAlt ]

- type: randomHumanoidSettings
  id: VisitorVirologist
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorVirologist, VisitorVirologistAlt ]

- type: randomHumanoidSettings
  id: VisitorGeneticist
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorGeneticist, VisitorGeneticistAlt ]

- type: randomHumanoidSettings
  id: VisitorPsychologist
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorPsychologist, VisitorPsychologistAlt ]

- type: randomHumanoidSettings
  id: VisitorChemist
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorChemist, VisitorChemistAlt ]

- type: randomHumanoidSettings
  id: VisitorDentist
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorDentist ]

# Science

- type: randomHumanoidSettings
  id: VisitorResearchAssistant
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorResearchAssistant, VisitorResearchAssistantAlt ]

- type: randomHumanoidSettings
  id: VisitorScientist
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorScientist, VisitorScientistAlt ]

# Civilian

- type: randomHumanoidSettings
  id: VisitorBartender
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorBartender, VisitorBartenderAlt ]

- type: randomHumanoidSettings
  id: VisitorBotanist
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorBotanist, VisitorBotanistAlt ]

- type: randomHumanoidSettings
  id: VisitorBoxer
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorBoxer, VisitorBoxerAlt ]

- type: randomHumanoidSettings
  id: VisitorChaplain
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorChaplain, VisitorChaplainAlt ]

- type: randomHumanoidSettings
  id: VisitorChef
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorChef, VisitorChefAlt ]

- type: randomHumanoidSettings
  id: VisitorClown
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorClown ]
      
- type: randomHumanoidSettings
  id: VisitorJanitor
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorJanitor, VisitorJanitorAlt ]

- type: randomHumanoidSettings
  id: VisitorLawyer
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorLawyer, VisitorLawyerAlt ]

- type: randomHumanoidSettings
  id: VisitorLibrarian
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorLibrarian, VisitorLibrarianAlt ]

- type: randomHumanoidSettings
  id: VisitorMusician
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorMusician, VisitorMusicianAlt ]

- type: randomHumanoidSettings
  id: VisitorMime
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorMime, VisitorMimeAlt ]

- type: randomHumanoidSettings
  id: VisitorReporter
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorReporter, VisitorReporterAlt ]

- type: randomHumanoidSettings
  id: VisitorServiceWorker
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorServiceWorker, VisitorServiceWorkerAlt ]

- type: randomHumanoidSettings
  id: VisitorZookeeper
  parent: EventHumanoid
  components:
    - type: GhostRole
      name: ghost-role-information-lost-cargo-technical-name
      description: ghost-role-information-lost-cargo-technical-description
      rules: ghost-role-information-lost-cargo-technical-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ VisitorZookeeper, VisitorZookeeperAlt ]






- type: randomHumanoidSettings
  id: ClownTroupeBanana
  parent: ClownTroupe
  randomizeName: false
  components:
    - type: Loadout
      prototypes: [ BananaClown ]

### Visitors with Visitor ID

# Command
# Following use EventHumanoidMindShielded since they are heads and probably should have mindshields

# Security
# Following use EventHumanoidMindShielded since they are heads and probably should have mindshields

# Misc

# Cargo

# Engineering

# Medical

# Science

# Civilian

### Visitors missing equipment for challenges
# CHALLENGE #
# these are specifically missing QOL equipment and have settings to make them harder.
# making changes to these should be done with care to avoid unbalancing challenging scenarios.

# Command
# Following use EventHumanoidMindShielded since they are heads and probably should have mindshields

- type: randomHumanoidSettings
  id: ChallengeVictimResearchDirector
  randomizeName: false
#  This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimRD, ChallengeVictimRDAlt ] #!!
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last

- type: randomHumanoidSettings
  id: ChallengeVictimCMO
  randomizeName: false
#  This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimCMO, ChallengeVictimCMOAlt ] #!!
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last

- type: randomHumanoidSettings
  id: ChallengeVictimCaptain
  randomizeName: false
#  This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-commander-name
      description: ghost-role-information-lost-challenge-commander-description
      rules: ghost-role-information-lost-challenge-commander-rules
      raffle:
        settings: default
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeVictimCaptain, ChallengeVictimCaptainAlt ] #!!
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last

# Security
# Following use EventHumanoidMindShielded since they are heads and probably should have mindshields

# Misc

# Cargo

- type: randomHumanoidSettings
  id: ChallengeCargoTechnician
  randomizeName: false
#  This is supposed to be for challenge events. Its intentionally missing QOL gear to make interesting scenarios.
  components:
    - type: GhostRole
      name: ghost-role-information-lost-challenge-cargo-technican-name
      description: ghost-role-information-lost-challenge-cargo-technican-description
      rules: ghost-role-information-lost-disaster-challenge-cargo-technican-rules
      raffle:
        settings: short
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ ChallengeCargoTechGearSuit, ChallengeCargoTechGearCoat ] #!!
    - type: RandomMetadata
      nameSegments:
      - names_first
      - names_last

# Engineering

# Medical

# Science

# Civilian

### Syndicate & Hostiles

- type: randomHumanoidSettings
  id: SyndieVisitor
  parent: EventHumanoid
  components:
    - type: NpcFactionMember
      factions:
      - Syndicate
    - type: GhostRole
      name: ghost-role-information-syndie-disaster-victim-name
      description: ghost-role-information-syndie-disaster-victim-description
      rules: ghost-role-information-syndie-disaster-victim-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes: [ SyndicateOperativeGearCivilian ]

### Other