# Base configs
- type: dungeonConfig
  id: PlanetBase
  layers:
  - !type:PrefabDunGen
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:CorridorPostGen
    width: 3

  - !type:DungeonEntrancePostGen
    count: 2

  - !type:RoomEntrancePostGen
    entities:
    - CableApcExtension
    - AirlockGlass

  - !type:EntranceFlankPostGen
    entities:
    - Grille
    - Window

  - !type:ExternalWindowPostGen
    entities:
    - Grille
    - Window

  - !type:WallMountPostGen

  - !type:BoundaryWallPostGen

  - !type:JunctionPostGen
    width: 1

  - !type:JunctionPostGen

  - !type:AutoCablingPostGen

  - !type:CornerClutterPostGen
    contents:
    - id: PottedPlantRandom
      amount: 1

  - !type:CorridorDecalSkirtingPostGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: dungeonConfig
  id: Mineshaft
  data:
    tiles:
      FallbackTile: FloorCaveDrought
    whitelist:
      Rooms:
        tags:
        - Mineshaft
  layers:
  - !type:PrefabDunGen
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:CorridorPostGen
    tile: FloorCaveDrought
    width: 3

  - !type:DungeonEntrancePostGen
    count: 5
    tile: FloorCaveDrought
    entities:
    - RandomWoodenWall

  - !type:RoomEntrancePostGen
    tile: FloorCaveDrought
    entities:
    - RandomWoodenWall

  - !type:EntranceFlankPostGen
    tile: FloorCaveDrought
    entities:
    - RandomWoodenWall

  - !type:ExternalWindowPostGen
    tile: FloorCaveDrought
    entities:
    - RandomWoodenWall

  - !type:WallMountPostGen

  - !type:BoundaryWallPostGen
    tile: FloorCaveDrought
    wall: WallRock
    cornerWall: WallRock

  - !type:AutoCablingPostGen
    entity: Catwalk

  - !type:JunctionPostGen
    tile: FloorCaveDrought
    width: 3
    entities:
    - RandomWoodenSupport

  - !type:CornerClutterPostGen
    contents:
    - id: RandomStalagmiteOrCrystal
      amount: 1

- type: dungeonConfig
  id: Haunted
  data:
    entities:
      Wall: WallRock
    tiles:
      FallbackTile: FloorCaveDrought
    whitelist:
      Rooms:
        tags:
        - Mineshaft
  layers:
  - !type:PrefabDunGen
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:WormCorridorPostGen
    width: 3
    tile: FloorCaveDrought

  - !type:CorridorClutterPostGen
    contents:
    - id: FloraStalagmite1
    - id: FloraStalagmite2
    - id: FloraStalagmite3
    - id: FloraStalagmite4
    - id: FloraStalagmite5
    - id: FloraStalagmite6

  - !type:BoundaryWallPostGen

# Setups
- type: dungeonConfig
  id: Experiment
  data:
    colors:
      Decals: "#D381C996"
    entities:
      CornerWalls: WallReinforced
      Entrance: AirlockGlass
      Intercom: IntercomCommon
      Walls: WallSolid
    spawnGroups:
      WallMounts: ScienceLabsWalls
    tiles:
      FallbackTile: FloorSteel
    whitelists:
      Rooms:
        tags:
        - SalvageExperiment
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

- type: dungeonConfig
  id: LavaBrig
  data:
    colors:
      Decals: "#DE3A3A96"
    entities:
      CornerWalls: WallReinforced
      Entrance: AirlockSecurityGlassLocked
      Walls: WallSolid
    spawnGroups:
      WallMounts: ScienceLabsWalls
    whitelists:
      Rooms:
        tags:
        - LavaBrig
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

- type: dungeonConfig
  id: SnowyLabs
  data:
    colors:
      Decals: "#4cc7aa96"
    entities:
      CornerWalls: WallSilver
      Entrance: AirlockFreezerHydroponicsLocked
      Walls: WallSilver
    spawnGroups:
      WallMounts: SnowyLabsWalls
    tiles:
      FallbackTile: FloorSteel
    whitelists:
      Rooms:
        tags:
        - SnowyLabs
  layers:
  - !type:PrototypeDunGen
    proto: PlanetBase

# Spawn groups
- type: entitySpawnEntry
  id: ScienceLabsWalls
  entries:
  # Posters
  - id: RandomPosterLegit
    orGroup: content
  - id: ExtinguisherCabinetFilled
    prob: 0.2
    orGroup: content
  - id: RandomPainting
    prob: 0.05
    orGroup: content
  - id: IntercomCommon
    prob: 0.1
    orGroup: content

- type: entitySpawnEntry
  id: MineshaftWalls
  entries:
  # Ore
  - id: WallRockSalt
    prob: 0.6
    orGroup: content
  - id: WallRockCoal
    prob: 0.6
    orGroup: content
  - id: WallRockTin
    prob: 0.4
    orGroup: content
  - id: WallMining
    prob: 0.8
    orGroup: content

- type: entitySpawnEntry
  id: SnowyLabsWalls
  entries:
  # Posters
  - id: RandomPosterLegit
    orGroup: content
  - id: ExtinguisherCabinetFilled
    prob: 0.2
    orGroup: content
  - id: RandomPainting
    prob: 0.05
    orGroup: content
  - id: IntercomScience
    prob: 0.1
    orGroup: content
