#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  storage:
    back:
    - BoxSurvival

#Deathsquad Outfit
- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    suitstorage: AirTankFilled
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: EnergySword
    pocket2: EnergyShield
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - BoxSurvivalEngineering
    - WeaponPulseRifle
    - WeaponPulsePistol
    - WeaponRevolverMateba
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxFlashbang
    - ToolDebug # spanish army knife
    - WelderExperimental
    - Hypospray
    - DeathAcidifierImplanter # crew will try to steal their amazing hardsuits
    - FreedomImplanter

# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlack
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicate

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  storage:
    back:
    - BoxSurvival

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  parent: SyndicateFootsoldierGearRuin
  equipment:
    ears: ClothingHeadsetAltSyndicate

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
    - MagazinePistol

#CBURN Unit Gear - Full Kit
- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    suitstorage: OxygenTankFilled
    belt: ClothingBeltBandolier
  storage:
    back:
    - BoxSurvivalEngineering
    - WeaponShotgunDoubleBarreled
    - BoxShotgunIncendiary
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    id: PunPunIDCard

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
  inhand:
    - WeaponMeleeToolboxRobust

#Brigmedic

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelHolding
    id: AdminPDA
  storage:
    back:
    - GasAnalyzer
    - trayScanner
    - AccessConfiguratorUniversal

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult

#Banana Clown
- type: startingGear
  id: BananaClown
  equipment:
    id: VisitorPDA
    back: ClothingBackpackClown
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana
    pocket1: BikeHorn
    pocket2: ClownRecorder

# Passenger but without the ID, bag, or headset
- type: startingGear
  id: LimitedPassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack

#Clown Troupe
- type: startingGear
  id: ClownTroupe
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    id: VisitorPDA
    back: ClothingBackpackClown
    ears: ClothingHeadsetService
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder

#Lost Cargo Tech
- type: startingGear
  id: LostCargoTechGearSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCargosoft
    id: VisitorPDA
    back: ClothingBackpackCargo
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool

- type: startingGear
  id: LostCargoTechGearCoat
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesBootsWinterCargo
    head: ClothingHeadHatCargosoft
    id: VisitorPDA
    back: ClothingBackpackDuffelCargo
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    outerClothing: ClothingOuterWinterCargo

#Traveling Chef
- type: startingGear
  id: TravelingChef
  equipment:
    jumpsuit: ClothingUniformJumpsuitChef
    shoes: ClothingShoesColorWhite
    id: VisitorPDA
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetService
    belt: ClothingBeltChef

#CMO Disaster Victim
- type: startingGear
  id: DisasterVictimCMO
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    shoes: ClothingShoesColorBrown
    head: ClothingHeadMirror
    neck: ClothingCloakCmo
    id: VisitorPDA
    back: ClothingBackpackMedical
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo

- type: startingGear
  id: DisasterVictimCMOAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMOTurtle
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretCmo
    neck: ClothingNeckMantleCMO
    id: VisitorPDA
    back: ClothingBackpackSatchelMedical
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo

#Captain Disaster Victim
- type: startingGear
  id: DisasterVictimCaptain
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCaptain
    neck: ClothingNeckCloakCap
    id: VisitorPDA
    back: ClothingBackpackCaptain
    ears: ClothingHeadsetAltCommand
    outerClothing: ClothingOuterArmorCaptainCarapace

- type: startingGear
  id: DisasterVictimCaptainAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCapFormal
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCapcap
    neck: ClothingNeckMantleCap
    id: VisitorPDA
    back: ClothingBackpackSatchelCaptain
    ears: ClothingHeadsetAltCommand
    outerClothing: ClothingOuterArmorCaptainCarapace

#RD Disaster Victim
- type: startingGear
  id: DisasterVictimRD
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckCloakRd
    id: VisitorPDA
    back: ClothingBackpackScience
    ears: ClothingHeadsetRD
    outerClothing: ClothingOuterCoatRD

- type: startingGear
  id: DisasterVictimRDAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckMantleRD
    id: VisitorPDA
    back: ClothingBackpackSatchelScience
    ears: ClothingHeadsetRD
    outerClothing: ClothingOuterCoatRD

# CHALLENGE
# carefully consider everything you add to these. These are meant for roles that are placed in survival situations where every item will be a resource.
# Challenge Cargo Tech
- type: startingGear
  id: ChallengeCargoTechGearSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCargosoft
    id: VisitorPDA
    back: ClothingBackpackCargo
    #ears: null # No headsets.
    pocket1: AppraisalTool

- type: startingGear
  id: ChallengeCargoTechGearCoat
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesBootsWinterCargo
    head: ClothingHeadHatCargosoft
    id: VisitorPDA
    back: ClothingBackpackSatchelCargo
    #ears: # No headsets.
    pocket1: AppraisalTool
    outerClothing: ClothingOuterWinterCargo

# CHALLENGE
# carefully consider everything you add to these. These are meant for roles that are placed in survival situations where every item will be a resource.
#CMO Disaster Victim
- type: startingGear
  id: ChallengeVictimCMO
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    shoes: ClothingShoesColorBrown
    head: ClothingHeadMirror
    neck: ClothingCloakCmo
    id: VisitorPDA
    back: ClothingBackpackMedical
    #ears: # No headsets.
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo

- type: startingGear
  id: ChallengeVictimCMOAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMOTurtle
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretCmo
    neck: ClothingNeckMantleCMO
    id: VisitorPDA
    back: ClothingBackpackSatchelMedical
    #ears: # No headsets.
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo

# CHALLENGE
# carefully consider everything you add to these. These are meant for roles that are placed in survival situations where every item will be a resource.
#Captain Disaster Victim
- type: startingGear
  id: ChallengeVictimCaptain
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCaptain
    neck: ClothingNeckCloakCap
    id: VisitorPDA
    back: ClothingBackpackCaptain
    #ears: # No headsets.

- type: startingGear
  id: ChallengeVictimCaptainAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCapFormal
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCapcap
    neck: ClothingNeckMantleCap
    id: VisitorPDA
    back: ClothingBackpackSatchelCaptain
    #ears: # No headsets.
    outerClothing: ClothingOuterWinterCap

# CHALLENGE
# carefully consider everything you add to these. These are meant for roles that are placed in survival situations where every item will be a resource.
#RD Disaster Victim
- type: startingGear
  id: ChallengeVictimRD
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckCloakRd
    id: VisitorPDA
    back: ClothingBackpackScience
    #ears: #No headsets.
    outerClothing: ClothingOuterCoatRD

- type: startingGear
  id: ChallengeVictimRDAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckMantleRD
    id: VisitorPDA
    back: ClothingBackpackSatchelScience
    #ears: # No headsets.
    outerClothing: ClothingOuterCoatRD
