# for important antag roles (nukie reinforcements, ninja, etc.)
- type: ghostRoleRaffleSettings
  id: default
  settings:
    initialDuration: 300
    joinExtendsDurationBy: 0
    maxDuration: 300

# for roles that don't matter too much or are available plentifully (e.g. space carp)
- type: ghostRoleRaffleSettings
  id: short
  settings:
    initialDuration: 60
    joinExtendsDurationBy: 3
    maxDuration: 120
